%part b of exercise 3, a 4x4 matrix is generated by hand
%then you execute linsolve and the back slash to see which one is better
%same sort of solution as my 3x3 example.
A= [1,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0;
    0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0;
    0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0;
    1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1;
    1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0;
    0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1;
    1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1;
    1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0;
    0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0;
    0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1;
    0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0;
    1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0;
    0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0;
    0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,0;
    0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0;
    1,1,1,1,1,0,1,0,0,0,1,0,0,0,0,1];
    
rank(A)
b = [13;15;8;14.79;14.31;3.81;18;12;6;10.51;16.13;7.04;12;1;23;1]; %my random b that i just made up, got a little lazy and included the values fromt he earlier one.
tic
slashx= A\b;
toc
cond(A);
imshow(slashx);%shows 1 line of different shades, because i didn't bother reshaping it
tic
linx=linsolve(A,b);
toc

%the same effect shows up as the last one.
%lin solve is more consistant where as the backslash is a lot less
%consistant in its time.