# A sample Makefile for the tar presentation.  Will not work for
# Assignments.
#
# Compiles hello.c

# normally, want to create .o files (need this for full marks on Assignments)
hello: hello.c
	gcc -Wall -std=c99 hello.c -o hello

# normally, want a clean target (need this for full marks on
# Assignments)
