#Eric Hsueh
#1384955
#makefile for q1, q2, q3, q4
q6: q6.c
	gcc -g q6.c -lsqlite3 -lm -o q6

q4: q4.c
	gcc -g q4.c -lsqlite3 -lm -o q4

q5: q5.c
	gcc -g q5.c -lsqlite3 -lm -o q5

q3: q3.c
	gcc -g q3.c -lsqlite3 -lm -o q3

q2: q2.c
	gcc -g q2.c -lsqlite3 -lm -o q2

q1: q1.c
	gcc -g q1.c -lsqlite3 -lm -o q1

clean:
	-rm -f q1 core
	-rm -f q2 core
	-rm -f q3 core
	-rm -f q4 core
	-rm -f q5 core
	-rm -f q6 core
